[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
DISABLE_ANALYTICS = "true"
DISABLE_COOKIE_CONSENT = "true" 